name: Go test workflow
on: [push]
#
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18.x', '1.19.x' ]
    #
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          #cache: true
      #
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      #
      #- name: Install dependencies
      #  run: go get .
      #
      - name: Build
        run: go build -v ./... 
      #
      - name: Test with the Go CLI
        run: go test -v ./... -json > TestResults-${{ matrix.go-version }}.json
      #
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
    #
  #
#